Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Karnel_Travel_Guide.Models;

namespace Karnel_Travel_Guide.Controllers
{
    public class CitiesController : Controller
    {
        private KarnelTravelDatabaseEntities db = new KarnelTravelDatabaseEntities();

        // GET: Cities
        public ActionResult Index()
        {
            return View(db.Cities.ToList());
        }

     

        // GET: Cities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cities/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "City_Id,City_Name")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Cities.Add(city);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(city);
        }

        // GET: Cities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "City_Id,City_Name")] City city)
        {
            if (ModelState.IsValid)
            {
                db.Entry(city).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(city);
        }

        // GET: Cities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            City city = db.Cities.Find(id);
            if (city == null)
            {
                return HttpNotFound();
            }
            return View(city);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            City city = db.Cities.Find(id);
            db.Cities.Remove(city);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/HotelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Karnel_Travel_Guide.Models;

namespace Karnel_Travel_Guide.Controllers
{
    public class HotelsController : Controller
    {
        private KarnelTravelDatabaseEntities db = new KarnelTravelDatabaseEntities();

        // GET: Hotels
        public ActionResult Index()
        {
            if (Session["a_id"] != null)
            {
                var hotels = db.Hotels.Include(h => h.City);
                return View(hotels.ToList());
            }
            else
            {
                return RedirectToAction("LogIn", controllerName: "FrontEnd");
            }

        }

       

        // GET: Hotels/Create
        public ActionResult Create()
        {
            if (Session["a_id"] != null)
            {
                ViewBag.Hotel_City = new SelectList(db.Cities, "City_Id", "City_Name");
                return View();
            }
            else
            {
                return RedirectToAction("LogIn", controllerName: "FrontEnd");
            }

        }

        // POST: Hotels/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Hotel hotel,HttpPostedFileBase hotelimg1,HttpPostedFileBase hotelimg2,HttpPostedFileBase hotelimg3)
        {
            if (ModelState.IsValid)
            {
                if (hotelimg1.ContentLength > 0)
                {

                    string fileName1 = hotelimg1.FileName;
                    hotelimg1.SaveAs(Server.MapPath("~/Content/images/" + fileName1));
                    hotelimg1.InputStream.Close();
                    hotelimg1.InputStream.Dispose();


                    if (hotelimg2.ContentLength > 0)
                    {
                        string fileName2 = hotelimg2.FileName;
                        hotelimg2.SaveAs(Server.MapPath("~/Content/images/" + fileName2));
                        hotelimg2.InputStream.Close();
                        hotelimg2.InputStream.Dispose();
                        hotel.Hotel_Image2 = fileName2;
                    }

                    if(hotelimg3.ContentLength > 0)
                    {
                        string fileName3 = hotelimg3.FileName;
                        hotelimg3.SaveAs(Server.MapPath("~/Content/images/" + fileName3));
                        hotelimg3.InputStream.Close();
                        hotelimg3.InputStream.Dispose();
                        hotel.Hotel_Image3 = fileName3;
                    }
                    hotel.Hotel_Image = fileName1;
                    db.Hotels.Add(hotel);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            ViewBag.Hotel_City = new SelectList(db.Cities, "City_Id", "City_Name", hotel.Hotel_City);
            return View(hotel);
        }

        // GET: Hotels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            ViewBag.Hotel_City = new SelectList(db.Cities, "City_Id", "City_Name", hotel.Hotel_City);
            return View(hotel);
        }

        // POST: Hotels/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Hotel hotel, HttpPostedFileBase hotelimg1, HttpPostedFileBase hotelimg2, HttpPostedFileBase hotelimg3)
        {
            if (ModelState.IsValid)
            {
                if (hotelimg1.ContentLength > 0)
                {

                    string fileName1 = hotelimg1.FileName;
                    hotelimg1.SaveAs(Server.MapPath("~/Content/images/" + fileName1));
                    hotelimg1.InputStream.Close();
                    hotelimg1.InputStream.Dispose();


                    if (hotelimg2.ContentLength > 0)
                    {
                        string fileName2 = hotelimg2.FileName;
                        hotelimg2.SaveAs(Server.MapPath("~/Content/images/" + fileName2));
                        hotelimg2.InputStream.Close();
                        hotelimg2.InputStream.Dispose();
                        hotel.Hotel_Image2 = fileName2;
                    }

                    if (hotelimg3.ContentLength > 0)
                    {
                        string fileName3 = hotelimg3.FileName;
                        hotelimg3.SaveAs(Server.MapPath("~/Content/images/" + fileName3));
                        hotelimg3.InputStream.Close();
                        hotelimg3.InputStream.Dispose();
                        hotel.Hotel_Image3 = fileName3;
                    }
                    hotel.Hotel_Image = fileName1;

                    db.Entry(hotel).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Hotel_City = new SelectList(db.Cities, "City_Id", "City_Name", hotel.Hotel_City);
            return View(hotel);
        }

        // GET: Hotels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hotel hotel = db.Hotels.Find(id);
            if (hotel == null)
            {
                return HttpNotFound();
            }
            return View(hotel);
        }

        // POST: Hotels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Hotel hotel = db.Hotels.Find(id);
            db.Hotels.Remove(hotel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/AdminLayout.cshtml

<!DOCTYPE html>
<html lang="en">

<!--   Tue, 07 Jan 2020 03:33:27 GMT -->
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>Karnel Travel Guide &mdash; Admin Dashboard</title>
    <link rel="icon" type="image/x-icon" href="~/Content/images/logo.png">

    <!-- General CSS Files -->
    <link rel="stylesheet" href="~/Content/assets/modules/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/assets/modules/fontawesome/css/all.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" />
    <!-- CSS Libraries -->
    <link rel="stylesheet" href="~/Content/assets/modules/jqvmap/dist/jqvmap.min.css">
    <link rel="stylesheet" href="~/Content/assets/modules/summernote/summernote-bs4.css">
    <link rel="stylesheet" href="~/Content/assets/modules/owlcarousel2/dist/assets/owl.carousel.min.css">
    <link rel="stylesheet" href="~/Content/assets/modules/owlcarousel2/dist/assets/owl.theme.default.min.css">

    <!-- Template CSS -->
    <link rel="stylesheet" href="~/Content/assets/css/style.min.css">
    <link rel="stylesheet" href="~/Content/assets/css/components.min.css">


    <style>
        .btn-primary {
            box-shadow: 0 2px 6px white;
            background-color: #673B31;
            border-color: #673B31;
            transition: 0.8s all ease-in-out;
        }

            .btn-primary:active, .btn-primary:hover, .btn-primary.disabled:active, .btn-primary.disabled:hover {
                box-shadow: 0 2px 6px #673B31;
                background-color: white !important;
                border-color: #673B31;
                color: #673B31;
            }

        h4 {
            color: #673B31;
        }

        .form-group .control-label, .form-group > label {
            font-weight: 600;
            color: #673B31;
            font-size: 12px;
            letter-spacing: .5px;
        }



        .navbar-bg {
            content: ' ';
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 115px;
            background-color: white;
            z-index: -1;
        }

        .input-group-text, select.form-control:not([size]):not([multiple]), .form-control:not(.form-control-sm):not(.form-control-lg) {
            font-size: 14px;
            padding: 10px 15px;
            height: 42px;
            border-color: #673B31;
            background-color: white;
            color: black;
            font-weight: 800;
        }

        .main-sidebar .sidebar-menu li a.has-dropdown:after {
            content: "􏁣";
            font-family: 'Font Awesome 5 Free';
            font-weight: 900;
            position: absolute;
            top: 50%;
            right: 20px;
            -webkit-transform: translate(0, -50%);
            transform: translate(0, -50%);
            font-size: 12px;
        }

        .shadow-primary {
            box-shadow: 0 2px 6px #7c2f11;
        }

        .bg-primary {
            background-color: #673B31 !important;
        }

        .btn-change6 {
            height: 50px;
            width: 100px;
            background: white;
            margin: 20px;
            float: left;
            border: 0px;
            font-family: cursive;
            font-size: 16px;
            font-weight: 900;
            color: #673B31;
            box-shadow: 0 0 1px #ccc;
            -webkit-transition-duration: 0.2s;
            -webkit-transition-timing-function: linear;
            box-shadow: 0px 0 0 #673B31 inset;
        }

            .btn-change6:hover {
                box-shadow: 0 0 0 25px #673B31 inset;
                color: white;
                -webkit-transform: scale(1);
            }
    
    </style>

</head>
<body class="layout-4">
    <!-- Page Loader -->
    <div class="page-loader-wrapper" style="background:#673B31;">
        <span class="loader"><span class="loader-inner"></span></span>
    </div>

    <div id="app">
        <div class="main-wrapper main-wrapper-1">
            <div class="navbar-bg"></div>

            <!-- Start app top navbar -->
            <nav class="navbar navbar-expand-lg main-navbar">
                <form class="form-inline mr-auto">
                    <ul class="navbar-nav mr-3">
                        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars" style="color:#673B31;"></i></a></li>

                    </ul>
                </form>
                <ul class="navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                            <img alt="image" src="~/Content/Admin/admin.jpg" class="rounded-circle mr-1">
                            <div class="d-sm-none d-lg-inline-block" style="color:#673B31;">Hi, Hamza!</div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <div class="dropdown-title">Logged in 5 min ago</div>
                            <a href="features-profile.html" class="dropdown-item has-icon"><i class="far fa-user"></i> Profile</a>

                            <div class="dropdown-divider"></div>
                            <a href="@Url.Action("LogOut","FrontEnd")" class="dropdown-item has-icon text-danger"><i class="fas fa-sign-out-alt"></i> Logout</a>
                        </div>
                    </li>
                </ul>
            </nav>

            <!-- Start main left sidebar menu -->
            <div class="main-sidebar sidebar-style-3" style="background-color: #673B31;">
                <aside id="sidebar-wrapper">
                    <div class="sidebar-brand">
                        <a href="@Url.Action("Home","FrontEnd")">KARNEL TRAVEL GUIDE</a>
                    </div>
                    <div class="sidebar-brand sidebar-brand-sm">
                        <a href="@Url.Action("Home","FrontEnd")" style="color:white;">KTG</a>
                    </div>
                    <ul class="sidebar-menu">
                        <li class="dropdown active">
                            <a href="#" class="nav-link" style="background-color: #673B31; box-shadow: 0 4px 8px #ffff;"><i class="fas fa-fire" style="color:white;"></i><span style="color:white;">Dashboard</span></a>

                        </li>

                        <li class="menu-header"></li>
                        <li class="dropdown">
                            <a href="#" class="nav-link has-dropdown" data-toggle="dropdown" style="background-color: #673B31;"><i class="fad fa-arrow-down" style="color:white;"></i> <span style="font-size:large; font-weight:900;">Create Services</span></a>
                            <ul class="dropdown-menu">
                                <li><a class="nav-link" href="@Url.Action("Create","Cities")"><i class="fas fa-city"></i> <span>City</span></a></li>
                                <li><a class="nav-link" href="@Url.Action("Create","Rest_Cat")"><i class="fad fa-utensils"></i><span>RestaurantCat</span></a></li>
                                <li><a class="nav-link" href="@Url.Action("Create","TouristSpots")"><i class="far fa-globe-asia"></i><span>TouristSpots</span></a></li>
                                <li><a class="nav-link" href="@Url.Action("Create","Travels")"><i class="fas fa-route"></i><span>Travels</span></a></li>
                                <li><a class="nav-link" href="@Url.Action("Create","Hotels")"><i class="fad fa-hotel"></i><span>Hotels</span></a></li>
                                <li><a class="nav-link" href="@Url.Action("Create","Restaurants")"><i class="far fa-utensils-alt"></i><span>Restaurants</span></a></li>
                                <li><a class="nav-link" href="@Url.Action("Create","Resorts")"><i class="fas fa-ski-lift"></i><span>Resorts</span></a></li>
                            </ul>
                        </li>


                        <li class="dropdown">
                            <a href="#" class="nav-link has-dropdown" data-toggle="dropdown" style="background-color: #673B31;"><i class="fad fa-arrow-down" style="color:white;"></i> <span style="font-size:large; font-weight:900;">Show Services</span></a>
                            <ul class="dropdown-menu">
                                <li><a class="nav-link" href="@Url.Action("Index","Cities")"><i class="fas fa-city"></i> <span>City</span></a></li>
                                <li><a class="nav-link" href="@Url.Action("Index","Rest_Cat")"><i class="fad fa-utensils"></i><span>RestaurantCat</span></a></li>
                                <li><a class="nav-link" href="@Url.Action("Index","TouristSpots")"><i class="far fa-globe-asia"></i><span>TouristSpots</span></a></li>
                                <li><a class="nav-link" href="@Url.Action("Index","Travels")"><i class="fas fa-route"></i><span>Travels</span></a></li>
                                <li><a class="nav-link" href="@Url.Action("Index","Hotels")"><i class="fad fa-hotel"></i><span>Hotels</span></a></li>
                                <li><a class="nav-link" href="@Url.Action("Index","Restaurants")"><i class="far fa-utensils-alt"></i><span>Restaurants</span></a></li>
                                <li><a class="nav-link" href="@Url.Action("Index","Resorts")"><i class="fas fa-ski-lift"></i><span>Resorts</span></a></li>
                            </ul>
                        </li>


                        <li><a class="nav-link" href="@Url.Action("Index","Bookings")"><i class="fal fa-book-reader"></i><span>Show Bookings</span></a></li>
                        <li><a class="nav-link" href="@Url.Action("LogOut","FrontEnd")" style="background-color: #673B31;"><i class="fas fa-sign-out-alt" style="color:white;"></i><span>Logout</span></a></li>
                    </ul>
                    
                </aside>
            </div>
            <!-- End of Topbar -->
            <div class="container-fluid">
                <div class="main-content">
                    <section class="section" style="color:#673B31;">
                        @RenderBody()
                    </section>
                </div>
            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- End of Main Content -->
        <!-- Start app Footer part -->
        <footer class="main-footer">
            <div class="footer-left">
            </div>
            <div class="footer-right">

            </div>
        </footer>
    </div>
    </div>

    <!-- General JS Scripts -->
    <script src="~/Content/assets/bundles/lib.vendor.bundle.js"></script>
    <script src="~/Content/Admin/js/CodiePie.js"></script>

    <!-- JS Libraies -->
    <script src="~/Content/assets/modules/jquery.sparkline.min.js"></script>
    <script src="~/Content/assets/modules/chart.min.js"></script>
    <script src="~/Content/assets/modules/owlcarousel2/dist/owl.carousel.min.js"></script>
    <script src="~/Content/assets/modules/summernote/summernote-bs4.js"></script>
    <script src="~/Content/assets/modules/chocolat/dist/js/jquery.chocolat.min.js"></script>

    <!-- Page Specific JS File -->
    <script src="~/Content/Admin/js/page/index.js"></script>

    <!-- Template JS File -->
    <script src="~/Content/Admin/js/scripts.js"></script>
    <script src="~/Content/Admin/js/custom.js"></script>
</body>

<!--   Tue, 07 Jan 2020 03:35:12 GMT -->
</html>

