Controllers/DetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Karnel_Travel_Guide.Models;

namespace Karnel_Travel_Guide.Controllers
{
    public class DetailsController : Controller
    {
        KarnelTravelDatabaseEntities db = new KarnelTravelDatabaseEntities();
        // GET: Details
        public ActionResult Tourist_Detail(int id)
        {
            TouristSpot touristSpot = db.TouristSpots.Where(x => x.Tour_Id == id).SingleOrDefault();
            return View(touristSpot);
        }

        public ActionResult Travel_Detail(int id)
        {
            Travel travel = db.Travels.Where(x => x.Tavel_Id == id).FirstOrDefault();
            return View(travel);
        }

        public ActionResult Hotel_Detail(int id)
        {
            Hotel hotel = db.Hotels.Where(x => x.Hotel_Id == id).FirstOrDefault();
            return View(hotel);
        }

        public ActionResult Restaurant_Detail(int id)
        {
            Restaurant restaurant = db.Restaurants.Where(x => x.Restaurant_Id == id).FirstOrDefault();
            return View(restaurant);
        }

        public ActionResult Resort_Detail(int id)
        {
            Resort resort = db.Resorts.Where(x => x.Resort_Id == id).FirstOrDefault();
            return View(resort);
        }
    }
}

Controllers/FrontEndController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Karnel_Travel_Guide.Models;

namespace Karnel_Travel_Guide.Controllers
{
    public class FrontEndController : Controller
    {
        KarnelTravelDatabaseEntities db = new KarnelTravelDatabaseEntities();
        public IEnumerable<Travel> tr;
        public IEnumerable<Hotel> he;

        public ActionResult Home()
        {
            return View();
        }

     
        public ActionResult Search(string searchBy,string search)
        {
            if (searchBy == "Tour_Designation")
            {
                var model = db.TouristSpots.Where(x => x.Tour_Designation == search || search == null).ToList();
                return View(model);
            }
            else
            {
                var model = db.TouristSpots.Where(x => x.Tour_Price == search || search == null).ToList();
                return View(model);

            }
            return View(db.TouristSpots.ToList());
        }

        public ActionResult AboutUs()
        {
            return View();
        }

        public ActionResult ContactUs()
        {
           
            return View();
        }

        [HttpPost]
        public ActionResult ContactUs(Cust_FeedBack cust_FeedBack)
        {
            db.Cust_FeedBack.Add(cust_FeedBack);
            db.SaveChanges();
            return View();
        }

        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        public ActionResult LogIn(string email, string password)
        {
            var user = db.User_Registration.Where(x => x.UserReg_Email == email && x.UserReg_Password == password).FirstOrDefault();
            var admin = db.Admins.Where(x => x.Admin_Email == email && x.Admin_Password == password).FirstOrDefault();
            if (user != null)
            {
                Session["u_img"] = user.UserReg_Image;
                Session["u_id"] = user.UserReg_Id;
                Session["u_name"] = user.UserReg_UserName;
                return RedirectToAction("Home", "FrontEnd");
            }
            else if (admin != null)
            {
                Session["a_id"] = admin.Admin_Id;
                Session["a_name"] = admin.AdminName;
                return RedirectToAction("AdminDashboard", "Admin");
            }
            ViewBag.msg = "Invalid Crenditeals";
            return View();
        }

        public ActionResult LogOut()
        {
            Session.RemoveAll();
            Session.Abandon();
            return RedirectToAction("Home", "FrontEnd");
        }




        public PartialViewResult partial_1()
        {

            tr = db.Travels.ToList();
            return PartialView("partial_1", tr);

        }


        public PartialViewResult partial_2()
        {

            he = db.Hotels.ToList();
            return PartialView("partial_2", he);

        }


    


    }
}

Views/FrontEnd/ContactUs.cshtml
@model Karnel_Travel_Guide.Models.Cust_FeedBack
@{
    ViewBag.Title = "ContactUs";
    Layout = "~/Views/Shared/FrontEndLayout.cshtml";
}


<style>
    .form_1 ul {
        padding: 0;
        overflow: hidden;
        margin-bottom: 0
    }

        .form_1 ul li {
            width: 50%;
            float: left;
            padding: 0 8px 16px;
            box-sizing: border-box
        }

            .form_1 ul li:last-child {
                padding-bottom: 0
            }

            .form_1 ul li input {
                border: 1px solid #bbb;
                width: 100%;
                padding: 10px;
                border-radius: 3px
            }

                .form_1 ul li input[placeholder], .form_1 ul li select {
                    color: #6b7a88
                }

            .form_1 ul li textarea {
                border: 1px solid #bbb;
                resize: none;
                border-radius: 3px;
                width: 100%
            }

            .form_1 ul li select {
                border: 1px solid #bbb;
                width: 100%;
                border-radius: 3px
            }

    .form_book ul li:nth-child(13) {
        width: 100%
    }

    .form_book ul li:nth-child(7) {
        width: 50% !important
    }

    .form_1 ul li:nth-child(7), .form_book_1 ul li:nth-child(11) {
        width: 100%
    }

        .form_1 ul li:nth-child(7) textarea {
            height: 120px;
            padding: 10px;
            background: #fff
        }

    .form_1 ul li input[type=submit] {
        font-weight: 700;
        text-decoration: none;
        color: #fff;
        padding: 12px 15px;
        border-radius: 2px;
        display: inline-block;
        background: #1aa5d8;
        background: #ff6a00;
        font-family: Quicksand,sans-serif;
        border: 0;
        text-transform: uppercase
    }

    .form {
        background-size: contain
    }

    .form_booking {
        background: url(../images/cloud.png) bottom center no-repeat #f2f8f9;
        padding: 100px 0 45px;
        background-size: contain
    }

    .form-spac {
        padding: 100px 0
    }
</style>

<section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url(/Content/images/bg3.jpg);">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1>Contact us</h1>
            </div>
        </div>
    </div>
</section>



<section class="ftco-section ftco-no-pb contact-section mb-4">
    <div class="container">
        <div class="row d-flex contact-info">
            <div class="col-md-3 d-flex">
                <div class="align-self-stretch box p-4 text-center">
                    <div class="icon d-flex align-items-center justify-content-center">
                        <span class="fa fa-map-marker"></span>
                    </div>
                    <h3 class="mb-2">Address</h3>
                    <p>198 West 21th Street, Suite 721 New York NY 10016</p>
                </div>
            </div>
            <div class="col-md-3 d-flex">
                <div class="align-self-stretch box p-4 text-center">
                    <div class="icon d-flex align-items-center justify-content-center">
                        <span class="fa fa-phone"></span>
                    </div>
                    <h3 class="mb-2">Contact Number</h3>
                    <p><a href="tel://1234567920">+ 92 3048350098</a></p>
                </div>
            </div>
            <div class="col-md-3 d-flex">
                <div class="align-self-stretch box p-4 text-center">
                    <div class="icon d-flex align-items-center justify-content-center">
                        <span class="fa fa-paper-plane"></span>
                    </div>
                    <h3 class="mb-2">Email Address</h3>
                    <p><a href="mailto:info@yoursite.com">karneltravel@yoursite.com</a></p>
                </div>
            </div>
            <div class="col-md-3 d-flex">
                <div class="align-self-stretch box p-4 text-center">
                    <div class="icon d-flex align-items-center justify-content-center">
                        <span class="fa fa-globe"></span>
                    </div>
                    <h3 class="mb-2">Website</h3>
                    <p><a href="#">www.karneltravelguide.com</a></p>
                </div>
            </div>
        </div>
    </div>
</section>


@using (Html.BeginForm("ContactUs", "FrontEnd", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="container jumbotron">
        <div class="rows">
            <div class="spe-title col-md-12">
                <h2 class="text-center">

                    <span>Feedback</span>
                </h2>
                <div class="title-line">
                    <div class="tl-1"></div>
                    <div class="tl-2"></div>
                    <div class="tl-3"></div>
                </div>
            </div>


            <div class="col-md-offset-2 col-md-8 col-sm-12 col-xs-12 form_1 wow fadeInLeft" data-wow-duration="1s" style="margin:0 auto;">
                @using (Html.BeginForm("ContactUs", "FrontEnd", FormMethod.Post))
                {

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                    <ul>
                        <li>
                            @Html.TextBoxFor(m => m.CusFeed_Name, new { placeholder = "Name" })


                        </li>


                        <li>
                            @Html.TextBoxFor(m => m.CusFeed_Email, new { placeholder = "Mobile" })


                        </li>
                        <li>
                            @Html.TextBoxFor(m => m.CusFeed_Phone, new { placeholder = "Email Id" })


                        </li>
                        <li>
                            @Html.TextBoxFor(m => m.CusFeed_Message, new { placeholder = "Message" })


                        </li>

                        <li>

                            <input type="submit" value="Submit" id="send_button" style="margin-left:50%;">

                        </li>
                        <li>
                            <p class="mt5">
                                <small>  @ViewBag.message</small><br />
                                @Html.ValidationMessageFor(model => model.CusFeed_Name, "", new { @class = "text-danger" })<br />
                                @Html.ValidationMessageFor(model => model.CusFeed_Email, "", new { @class = "text-danger" })<br />
                                @Html.ValidationMessageFor(model => model.CusFeed_Phone, "", new { @class = "text-danger" })<br />
                                @Html.ValidationMessageFor(model => model.CusFeed_Message, "", new { @class = "text-danger" })<br />
                            </p>


                        </li>

                    </ul>

                }



            </div>
        </div>
    </div>

}


<div class="container">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3618.1393054807736!2d67.03085831452483!3d24.92732384871451!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33f90157042d3%3A0x93d609e8bec9a880!2sAptech%20Computer%20Education%20North%20Nazimabad%20Center!5e0!3m2!1sen!2s!4v1640161639755!5m2!1sen!2s" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
</div>



<section class="ftco-intro ftco-section ftco-no-pt">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <div class="img" style="background-image: url(images/bg_2.jpg);">
                    <div class="overlay"></div>
                    <h2>We Are Pacific A Travel Agency</h2>
                    <p>We can manage your dream building A small river named Duden flows by their place</p>
                    <p class="mb-0"><a href="#" class="btn btn-primary px-4 py-3">Ask For A Quote</a></p>
                </div>
            </div>
        </div>
    </div>
</section>

Views/FrontEnd/LogIn.cshtml

@{
    ViewBag.Title = "LogIn";
}

<!DOCTYPE html>

<html>
<head>
    <title>Karnel Travel Guide | Login</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Font Icon -->
    <link rel="stylesheet" href="~/Content/Login Content/fonts/material-icon/css/material-design-iconic-font.min.css">

    <!-- Main css -->
    <link rel="stylesheet" href="~/Content/Login Content/css/style.css">

    <style>
        .form-submit{
            cursor:pointer;
        }
        </style>
</head>


<body>
    @using (Html.BeginForm("Login", "FrontEnd", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="text"><span style="color:  #673B31;">KARNEL</span>TRAVLES</div>
        <div class="text1">
            <p>
                Karnel Travels is a Tours and Travels Company which provides the various transportation facilities
                between the cities like tourist spots, transportation between different cities in the country, also
                provides accommodations in hotels, etc.
            </p>
        </div>
        <section class="signup">

            <div class="content">
                <div class="signup-content">
                    <form id="signup-form" class="signup-form">
                        <h2 class="form-title">LOGIN</h2>
                        <div class="form-group">
                            <input type="text" class="form-input" name="email" id="name" placeholder="Enter Your Email" />
                            <span style="color:red;">@ViewBag.msg</span>
                        </div>

                        <div class="form-group">
                            <input type="password" class="form-input" name="password" id="password"
                                   placeholder="Enter Your Password" />
                            <span toggle="#password" class="zmdi zmdi-eye field-icon toggle-password"></span>
                            <span style="color:red;">@ViewBag.msg</span>
                        </div>

                        <div class="form-group">
                            <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                            <label for="agree-term" class="label-agree-term">
                                <span><span></span></span>I agree all
                                statements in <a href="#" class="term-service">Terms of service</a>
                            </label>
                        </div>
                        <div class="form-group">
                            <input type="submit" name="submit" id="submit" class="form-submit" value="LOGIN" />
                        </div>
                    </form>
                    <p class="loginhere">
                       Did'nt Have an account ? <a href="@Url.Action("UserSignup","userReg")" class="loginhere-link">Signup Here</a>
                    </p>
                </div>
            </div>
        </section>



    }

    <!-- JS -->
    <script src="~/Content/Login Content/vendor/jquery/jquery.min.js"></script>
    <script src="~/Content/Login Content/js/main.js"></script>


</body>
</html>

Views/FrontEnd/Search.cshtml
@model IEnumerable<Karnel_Travel_Guide.Models.TouristSpot>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/FrontEndLayout.cshtml";
}
<style>
   .example .form-control[type=text] {
        padding: 10px;
        font-size: 17px;
        border: 1px solid grey;
        float: left;
        width: 80%;
        background: #f1f1f1;
    }


    .example button {
        float: left;
        width: 20%;
        padding: 10px;
        background: #f15d30;
        color: white;
        font-size: 17px;
       border:none;
        cursor: pointer;
    }

    .example::after {
        content: "";
        clear: both;
        display: table;
    }
</style>



<section class="hero-wrap" style="background-image: url(/Content/images/bg_5.jpg); height:400px;"> 
    <div class="overlay">
        <div class="col-md-9 ftco-animate pb-5 text-center">
            <h1>Search</h1>
        </div>
    </div>
</section>



<div class="jumbotron">
    <div class="example">
        @using (Html.BeginForm("Search", "FrontEnd", FormMethod.Get))
        {
            @Html.TextBox("Search", "", new { @placeholder = "Searching...", @class = "form-control" })
            <button type="submit">Search</button>

            @Html.RadioButton("search", "Tour_Designation", true)<b>Tour Designation</b>
            @Html.RadioButton("search", "")<b>Tour Price</b>
        }
    </div>
</div>

<section class="ftco-section">
    <div class="container">
        <div class="row">



            @foreach (var item in Model)
            {


                <div class="col-md-4 ftco-animate">
                    <div class="project-wrap">
                        <a href="#" class="img" style="background-image: url(/Content/images/@item.Tour_Image);">
                            <span class="price">@item.Tour_Price</span>
                        </a>
                        <div class="text p-4">
                            <h3><a href="#">@item.Tour_Designation</a></h3>
                            <p class="location"><span class="fa fa-map-marker"></span>@item.City.City_Name</p>
                            <p class="location"><span>Discription : </span>@item.Tour_Discription</p>
                            <p class="mb-0"><a href="@Url.Action("Tourist_Detail","Details",new{id = item.Tour_Id})" class="btn btn-primary px-4 py-3">Show Details</a></p>
                        </div>
                    </div>
                </div>

            }


        </div>
    </div>
</section>





Views/FrontEnd/partial_1.cshtml
@model IEnumerable<Karnel_Travel_Guide.Models.Travel>




<section class="ftco-section">
    <div class="container">
        <div class="row">

            <div class="col">
                <h2 class="intro_title text-center">We have the best Traveling Services</h2>
            </div>

            <div class="row jumbotron">
                <div class="col-lg-10 offset-lg-1">
                    <div class="intro_text text-center">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu convallis tortor. Suspendisse potenti. In faucibus massa arcu, vitae cursus mi hendrerit nec. </p>
                    </div>
                </div>
            </div>


            @{ int count = 0;}

            @foreach (var item in Model)
            {
                if (count >= 6)
                {
                    break;
                }

                    <div class="col-md-4 ftco-animate">
                        <div class="project-wrap">
                            <a href="#" class="img" style="background-image: url(/Content/images/@item.Travel_Image);">
                                <span class="price">Rent : @item.Travel_Rent</span>
                            </a>
                            <div class="text p-4">
                                <span class="days">Type : @item.Travel_Type</span>
                                <h3><a href="#">@item.Travel_vehicles</a></h3>
                                <p class="location"><span class="far fa-people-arrows">Capacity : </span>@item.Travel_Capacity</p>
                                <p class="mb-0"><a href="@Url.Action("Travel_Detail","Details",new{id = item.Tavel_Id})" class="btn btn-primary px-4 py-3">Show Details</a></p>
                            </div>
                        </div>
                    </div>
                
            }


        </div>
    </div>
</section>

Views/FrontEnd/partial_2.cshtml
@model IEnumerable<Karnel_Travel_Guide.Models.Hotel>



<section class="ftco-section">
    <div class="container">
        <div class="row">

            <div class="col">
                <h2 class="intro_title text-center">We have the best Hotel services</h2>
            </div>

            <div class="row  jumbotron">
                <div class="col-lg-10 offset-lg-1">
                    <div class="intro_text text-center">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu convallis tortor. Suspendisse potenti. In faucibus massa arcu, vitae cursus mi hendrerit nec. </p>
                    </div>
                </div>
            </div>

            @{ int count = 0;}

            @foreach (var item in Model)
            {
                if (count >= 6)
                {
                    break;
                }

                <div class="col-md-4 ftco-animate">
                    <div class="project-wrap">
                        <a href="#" class="img" style="background-image: url(/Content/images/@item.Hotel_Image);">
                            <span class="price">Price Range : @item.Hotel_PriceRange</span>
                        </a>
                        <div class="text p-4">
                            <h3><a href="#">@item.Hotel_Name</a></h3>
                            <p class="location"><span class="fa fa-map-marker"></span>@item.City.City_Name</p>
                            <p class="location"><span>Discription : </span>@item.Hotel_Discription</p>
                            <p class="mb-0"><a href="@Url.Action("Hotel_Detail","Details",new{id = item.Hotel_Id})" class="btn btn-primary px-4 py-3">Show Details</a></p>
                        </div>
                    </div>
                </div>

            }








        </div>
    </div>
</section>