Models/TouristSpot.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Guide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TouristSpot
    {
        public int Tour_Id { get; set; }
        public string Tour_Designation { get; set; }
        public string Tour_Price { get; set; }
        public string Tour_Image { get; set; }
        public string Tour_Image2 { get; set; }
        public string Tour_Image3 { get; set; }
        public string Tour_Discription { get; set; }
        public int Tour_City { get; set; }
    
        public virtual City City { get; set; }
    }
}

Controllers/TouristSpotsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Karnel_Travel_Guide.Models;

namespace Karnel_Travel_Guide.Controllers
{
    public class TouristSpotsController : Controller
    {
        private KarnelTravelDatabaseEntities db = new KarnelTravelDatabaseEntities();

        // GET: TouristSpots
        public ActionResult Index()
        {
            if(Session["a_id"] != null)
            {
                var touristSpots = db.TouristSpots.Include(t => t.City);
                return View(touristSpots.ToList());
            }
            else
            {
                return RedirectToAction("LogIn", controllerName: "FrontEnd");
            }
          
        }

        

        // GET: TouristSpots/Create
        public ActionResult Create()
        {
            if(Session["a_id"]!= null)
            {
                ViewBag.Tour_City = new SelectList(db.Cities, "City_Id", "City_Name");
                return View();
            }
            else
            {
                return RedirectToAction("LogIn", controllerName: "FrontEnd");
            }

        }

        // POST: TouristSpots/Create
      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(TouristSpot touristSpot, HttpPostedFileBase tourimg1, HttpPostedFileBase tourimg2, HttpPostedFileBase tourimg3)
        {
            if (ModelState.IsValid)
            {
                if (tourimg1.ContentLength > 0)
                {
                    string fileName1 = tourimg1.FileName;
                    tourimg1.SaveAs(Server.MapPath("~/Content/images/" + fileName1));
                    tourimg1.InputStream.Close();
                    tourimg1.InputStream.Dispose();

                    if (tourimg2.ContentLength > 0)
                    {
                        string fileName2 = tourimg2.FileName;
                        tourimg2.SaveAs(Server.MapPath("~/Content/images/" + fileName2));
                        tourimg2.InputStream.Close();
                        tourimg2.InputStream.Dispose();
                        touristSpot.Tour_Image2 = fileName2;
                    }

                    if (tourimg3.ContentLength > 0)
                    {
                        string fileName3 = tourimg3.FileName;
                        tourimg3.SaveAs(Server.MapPath("~/Content/images/" + fileName3));
                        tourimg3.InputStream.Close();
                        tourimg3.InputStream.Dispose();
                        touristSpot.Tour_Image3 = fileName3;
                    }

                    touristSpot.Tour_Image = fileName1;
                    db.TouristSpots.Add(touristSpot);
                    db.SaveChanges();
                    return RedirectToAction("Create");
                }
            }

            ViewBag.Tour_City = new SelectList(db.Cities, "City_Id", "City_Name", touristSpot.Tour_City);
            return View(touristSpot);
        }

        // GET: TouristSpots/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TouristSpot touristSpot = db.TouristSpots.Find(id);
            if (touristSpot == null)
            {
                return HttpNotFound();
            }
            ViewBag.Tour_City = new SelectList(db.Cities, "City_Id", "City_Name", touristSpot.Tour_City);
            return View(touristSpot);
        }

        // POST: TouristSpots/Edit/5
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TouristSpot touristSpot,HttpPostedFileBase tourimg1, HttpPostedFileBase tourimg2, HttpPostedFileBase tourimg3)
        {
            if (ModelState.IsValid)
            {
                if(tourimg1.ContentLength > 0)
                {
                    string fileName1 = tourimg1.FileName;
                    tourimg1.SaveAs(Server.MapPath("~/Content/images/" + fileName1));
                    tourimg1.InputStream.Close();
                    tourimg1.InputStream.Dispose();

                  if(tourimg2.ContentLength > 0)
                    {
                        string fileName2 = tourimg2.FileName;
                        tourimg2.SaveAs(Server.MapPath("~/Content/images/" + fileName2));
                        tourimg2.InputStream.Close();
                        tourimg2.InputStream.Dispose();
                        touristSpot.Tour_Image2 = fileName2;
                    }

                  if(tourimg3.ContentLength > 0)
                    {
                        string fileName3 = tourimg3.FileName;
                        tourimg3.SaveAs(Server.MapPath("~/Content/images/" + fileName3));
                        tourimg3.InputStream.Close();
                        tourimg3.InputStream.Dispose();
                        touristSpot.Tour_Image3 = fileName3;
                    }

                    touristSpot.Tour_Image = fileName1;
                    db.Entry(touristSpot).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                
            }
            ViewBag.Tour_City = new SelectList(db.Cities, "City_Id", "City_Name", touristSpot.Tour_City);
            return View(touristSpot);
        }

        // GET: TouristSpots/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TouristSpot touristSpot = db.TouristSpots.Find(id);
            if (touristSpot == null)
            {
                return HttpNotFound();
            }
            return View(touristSpot);
        }

        // POST: TouristSpots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TouristSpot touristSpot = db.TouristSpots.Find(id);
            db.TouristSpots.Remove(touristSpot);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/TouristSpots/Create.cshtml
@model Karnel_Travel_Guide.Models.TouristSpot

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}



@using (Html.BeginForm("Create","TouristSpots",FormMethod.Post,new { enctype ="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TouristSpot</h4>
    
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Designation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tour_Designation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tour_Designation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tour_Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tour_Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Tour_Image, new { htmlAttributes = new { @class = "form-control" } })*@

                <input type="file" name="tourimg1" />
                @Html.ValidationMessageFor(model => model.Tour_Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Image2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Tour_Image2, new { htmlAttributes = new { @class = "form-control" } })*@

                <input type="file" name="tourimg2" />
                @Html.ValidationMessageFor(model => model.Tour_Image2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Image3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Tour_Image3, new { htmlAttributes = new { @class = "form-control" } })*@

                <input type="file" name="tourimg3" />
                @Html.ValidationMessageFor(model => model.Tour_Image3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Discription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tour_Discription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tour_Discription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_City, "Tour_City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Tour_City", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Tour_City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn-change6" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/TouristSpots/Delete.cshtml
@model Karnel_Travel_Guide.Models.TouristSpot

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TouristSpot</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tour_Designation)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tour_Designation)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tour_Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tour_Price)
        </dd>

        <dt>
            <img src="@Url.Content("~/Content/images/"+Model.Tour_Image)" width="200px" height="200px" />
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tour_Image)
        </dd>

        <dt>
            <img src="@Url.Content("~/Content/images/"+Model.Tour_Image2)" width="200px" height="200px" />
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tour_Image2)
        </dd>

        <dt>
            <img src="@Url.Content("~/Content/images/"+Model.Tour_Image3)" width="200px" height="200px" />
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tour_Image3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tour_Discription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tour_Discription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City.City_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.City_Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/TouristSpots/Edit.cshtml
@model Karnel_Travel_Guide.Models.TouristSpot

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit", "TouristSpots", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TouristSpot</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Tour_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Designation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tour_Designation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tour_Designation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tour_Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tour_Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Tour_Image, new { htmlAttributes = new { @class = "form-control" } })*@

                <input type="file" name="tourimg1" />
                @Html.ValidationMessageFor(model => model.Tour_Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Image2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Tour_Image2, new { htmlAttributes = new { @class = "form-control" } })*@

                <input type="file" name="tourimg2" />
                @Html.ValidationMessageFor(model => model.Tour_Image2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Image3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Tour_Image3, new { htmlAttributes = new { @class = "form-control" } })*@

                <input type="file" name="tourimg3" />
                @Html.ValidationMessageFor(model => model.Tour_Image3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_Discription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Tour_Discription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Tour_Discription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Tour_City, "Tour_City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Tour_City", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Tour_City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/TouristSpots/Index.cshtml
@model IEnumerable<Karnel_Travel_Guide.Models.TouristSpot>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Tour_Designation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tour_Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tour_Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tour_Image2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tour_Image3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tour_Discription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City.City_Name)
            </th>

            <th>
                <h4>Actions</h4>
            </th>
            <th></th>
        </tr>
    </thead>
@foreach (var item in Model) {
    <tbody>
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Tour_Designation)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tour_Price)
        </td>
        <td>
         <img src="~/Content/images/@Url.Content(item.Tour_Image)" width="100px" height="100px" />
        </td>
        <td>
            <img src="~/Content/images/@Url.Content(item.Tour_Image2)" width="100px" height="100px" />
        </td>
        <td>
            <img src="~/Content/images/@Url.Content(item.Tour_Image3)" width="100px" height="100px" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tour_Discription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City.City_Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Tour_Id }, new { @class = "btn btn-success" })
            @Html.ActionLink("Delete", "Delete", new { id=item.Tour_Id }, new { @class = "btn btn-danger" })
        </td>
    </tr>
        </tbody>
}

</table>