Models/Restaurant.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karnel_Travel_Guide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public int Restaurant_Id { get; set; }
        public string Restaurant_Name { get; set; }
        public string Restaurant_PriceRange { get; set; }
        public string Restaurant_Rating { get; set; }
        public string Restaurant_Image { get; set; }
        public string Restaurant_Image2 { get; set; }
        public string Restaurant_Image3 { get; set; }
        public string Restaurant_Discription { get; set; }
        public int Restaurant_City { get; set; }
        public int Restaurant_Catagories { get; set; }
    
        public virtual City City { get; set; }
        public virtual Rest_Cat Rest_Cat { get; set; }
    }
}

Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Karnel_Travel_Guide.Models;

namespace Karnel_Travel_Guide.Controllers
{
    public class RestaurantsController : Controller
    {
        private KarnelTravelDatabaseEntities db = new KarnelTravelDatabaseEntities();

        // GET: Restaurants
        public ActionResult Index()
        {
            if (Session["a_id"]!= null)
            {
                var restaurants = db.Restaurants.Include(r => r.City).Include(r => r.Rest_Cat);
                return View(restaurants.ToList());
            }
            else
            {
                return RedirectToAction("LogIn", controllerName: "FrontEnd");
            }

        }

    

        // GET: Restaurants/Create
        public ActionResult Create()
        {
            if (Session["a_id"] != null)
            {
                ViewBag.Restaurant_City = new SelectList(db.Cities, "City_Id", "City_Name");
                ViewBag.Restaurant_Catagories = new SelectList(db.Rest_Cat, "RestCat_Id", "ResCat_Name");
                return View();
            }
            else
            {
                return RedirectToAction("LogIn", controllerName: "FrontEnd");
            }

        }

        // POST: Restaurants/Create
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Restaurant restaurant,HttpPostedFileBase resimg1 , HttpPostedFileBase resimg2, HttpPostedFileBase resimg3)
        {
            if (ModelState.IsValid)
            {
                if(resimg1.ContentLength > 0)
                {
                    string fileName1 = resimg1.FileName;
                    resimg1.SaveAs(Server.MapPath("~/Content/images/" + fileName1));
                    resimg1.InputStream.Close();
                    resimg1.InputStream.Dispose();

                    if(resimg2.ContentLength > 0)
                    {
                        string fileName2 = resimg2.FileName;
                        resimg2.SaveAs(Server.MapPath("~/Content/images/" + fileName2));
                        resimg2.InputStream.Close();
                        resimg2.InputStream.Dispose();
                        restaurant.Restaurant_Image2 = fileName2;
                    }

                    if(resimg3.ContentLength > 0)
                    {
                        string fileName3 = resimg3.FileName;
                        resimg3.SaveAs(Server.MapPath("~/Content/images/" + fileName3));
                        resimg3.InputStream.Close();
                        resimg3.InputStream.Dispose();
                        restaurant.Restaurant_Image3 = fileName3;
                    }

                    restaurant.Restaurant_Image = fileName1;
                    db.Restaurants.Add(restaurant);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
               
            }

            ViewBag.Restaurant_City = new SelectList(db.Cities, "City_Id", "City_Name", restaurant.Restaurant_City);
            ViewBag.Restaurant_Catagories = new SelectList(db.Rest_Cat, "RestCat_Id", "ResCat_Name", restaurant.Restaurant_Catagories);
            return View(restaurant);
        }

        // GET: Restaurants/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurant restaurant = db.Restaurants.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            ViewBag.Restaurant_City = new SelectList(db.Cities, "City_Id", "City_Name", restaurant.Restaurant_City);
            ViewBag.Restaurant_Catagories = new SelectList(db.Rest_Cat, "RestCat_Id", "ResCat_Name", restaurant.Restaurant_Catagories);
            return View(restaurant);
        }

        // POST: Restaurants/Edit/5
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Restaurant restaurant,HttpPostedFileBase resimg1 , HttpPostedFileBase resimg2, HttpPostedFileBase resimg3)
        {
            if (ModelState.IsValid)
            {
                if (resimg1.ContentLength > 0)
                {
                    string fileName1 = resimg1.FileName;
                    resimg1.SaveAs(Server.MapPath("~/Content/images/" + fileName1));
                    resimg1.InputStream.Close();
                    resimg1.InputStream.Dispose();

                    if (resimg2.ContentLength > 0)
                    {
                        string fileName2 = resimg2.FileName;
                        resimg2.SaveAs(Server.MapPath("~/Content/images/" + fileName2));
                        resimg2.InputStream.Close();
                        resimg2.InputStream.Dispose();
                        restaurant.Restaurant_Image2 = fileName2;
                    }

                    if (resimg3.ContentLength > 0)
                    {
                        string fileName3 = resimg3.FileName;
                        resimg3.SaveAs(Server.MapPath("~/Content/images/" + fileName3));
                        resimg3.InputStream.Close();
                        resimg3.InputStream.Dispose();
                        restaurant.Restaurant_Image3 = fileName3;
                    }

                    restaurant.Restaurant_Image = fileName1;
                    db.Entry(restaurant).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Restaurant_City = new SelectList(db.Cities, "City_Id", "City_Name", restaurant.Restaurant_City);
            ViewBag.Restaurant_Catagories = new SelectList(db.Rest_Cat, "RestCat_Id", "ResCat_Name", restaurant.Restaurant_Catagories);
            return View(restaurant);
        }

        // GET: Restaurants/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Restaurant restaurant = db.Restaurants.Find(id);
            if (restaurant == null)
            {
                return HttpNotFound();
            }
            return View(restaurant);
        }

        // POST: Restaurants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Restaurant restaurant = db.Restaurants.Find(id);
            db.Restaurants.Remove(restaurant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Restaurants/Create.cshtml
@model Karnel_Travel_Guide.Models.Restaurant

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}



@using (Html.BeginForm("Create","Restaurants",FormMethod.Post,new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Restaurant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_PriceRange, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_PriceRange, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_PriceRange, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Restaurant_Image, new { htmlAttributes = new { @class = "form-control" } })*@

                <input type="file" name="resimg1" />
                @Html.ValidationMessageFor(model => model.Restaurant_Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_Image2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Restaurant_Image2, new { htmlAttributes = new { @class = "form-control" } })*@

                <input type="file" name="resimg2" />
                @Html.ValidationMessageFor(model => model.Restaurant_Image2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_Image3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Restaurant_Image3, new { htmlAttributes = new { @class = "form-control" } })*@

                <input type="file" name="resimg3" />
                @Html.ValidationMessageFor(model => model.Restaurant_Image3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_Discription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_Discription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_Discription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_City, "Restaurant_City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Restaurant_City", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Restaurant_City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_Catagories, "Restaurant_Catagories", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Restaurant_Catagories", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Restaurant_Catagories, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn-change6" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Restaurants/Delete.cshtml
@model Karnel_Travel_Guide.Models.Restaurant

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/Adminlayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Restaurant</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Restaurant_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurant_PriceRange)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_PriceRange)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurant_Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_Rating)
        </dd>

        <dt>
            <img src="@Url.Content("~/Content/images/"+Model.Restaurant_Image)" width="200px" height="200px" />
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_Image)
        </dd>

        <dt>
            <img src="@Url.Content("~/Content/images/"+Model.Restaurant_Image2)" width="200px" height="200px" />
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_Image2)
        </dd>

        <dt>
            <img src="@Url.Content("~/Content/images/"+Model.Restaurant_Image3)" width="200px" height="200px" />
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_Image3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Restaurant_Discription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Restaurant_Discription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City.City_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City.City_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rest_Cat.ResCat_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rest_Cat.ResCat_Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn-change6" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Restaurants/Edit.cshtml
@model Karnel_Travel_Guide.Models.Restaurant

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Edit","Restaurants",FormMethod.Post,new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Restaurant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Restaurant_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_PriceRange, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_PriceRange, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_PriceRange, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Restaurant_Image, new { htmlAttributes = new { @class = "form-control" } })*@

                <input type="file" name="resimg1" />
                @Html.ValidationMessageFor(model => model.Restaurant_Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_Image2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Restaurant_Image2, new { htmlAttributes = new { @class = "form-control" } })*@

                <input type="file" name="resimg2" />
                @Html.ValidationMessageFor(model => model.Restaurant_Image2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_Image3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Restaurant_Image3, new { htmlAttributes = new { @class = "form-control" } })*@

                <input type="file" name="resimg3" />
                @Html.ValidationMessageFor(model => model.Restaurant_Image3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_Discription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Restaurant_Discription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Restaurant_Discription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_City, "Restaurant_City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Restaurant_City", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Restaurant_City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Restaurant_Catagories, "Restaurant_Catagories", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Restaurant_Catagories", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Restaurant_Catagories, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn-change6" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Restaurants/Index.cshtml
@model IEnumerable<Karnel_Travel_Guide.Models.Restaurant>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table table-responsive">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Restaurant_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Restaurant_PriceRange)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Restaurant_Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Restaurant_Image)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Restaurant_Image2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Restaurant_Image3)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Restaurant_Discription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City.City_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rest_Cat.ResCat_Name)
            </th>
            <th></th>
        </tr>
    </thead>
@foreach (var item in Model)
{
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Restaurant_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Restaurant_PriceRange)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Restaurant_Rating)
            </td>
            <td>
                <img src="~/Content/images/@Url.Content(item.Restaurant_Image)" width="100px" height="100px" />
            </td>
            <td>
                <img src="~/Content/images/@Url.Content(item.Restaurant_Image2)" width="100px" height="100px" />
            </td>
            <td>
                <img src="~/Content/images/@Url.Content(item.Restaurant_Image3)" width="100px" height="100px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Restaurant_Discription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City.City_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rest_Cat.ResCat_Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Restaurant_Id }, new { @class = "btn btn-success" })
                @Html.ActionLink("Delete", "Delete", new { id = item.Restaurant_Id }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    </tbody>
}

</table>